version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres